repos:
  - repo: local
    hooks:
      # --- COMMIT STAGE: Fast unit tests only ---
      - id: ruff-check
        name: Run ruff linter
        entry: .venv/bin/python -m ruff check
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest-unit-no-jit
        name: Run JIT-disabled unit tests 
        entry: .venv/bin/python -m pytest tests/unit/disable_jit -m "not slow" --tb=short -q
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest-unit-jit
        name: Run JIT-enabled unit tests 
        entry: .venv/bin/python -m pytest tests/unit/dont_disable_jit -m "not slow" --tb=short -q
        language: system
        pass_filenames: false
        stages: [pre-commit]

      # --- PUSH STAGE: Complete test suite ---

      - id: pytest-unit-api
        name: Run pyreason api unit tests 
        entry: .venv/bin/python -m pytest tests/unit/api_tests --tb=short -q
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: pytest-functional-complete
        name: Run functional test suite
        entry: .venv/bin/python -m pytest tests/functional/ --tb=short
        language: system
        pass_filenames: false
        stages: [pre-push]
