repos:
  - repo: local
    hooks:
      # --- COMMIT STAGE: Fast unit tests only ---
      - id: pytest-unit-no-jit
        name: Run JIT-disabled unit tests 
        entry: .venv/bin/python -m pytest tests/unit/disable_jit -m "not slow" --tb=short -q
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest-unit-jit
        name: Run JIT-enabled unit tests 
        entry: .venv/bin/python -m pytest tests/unit/dont_disable_jit -m "not slow" --tb=short -q
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest-unit-api
        name: Run API unit tests
        entry: .venv/bin/python -m pytest tests/unit/api_tests -m "not slow" --tb=short -q
        language: system
        pass_filenames: false
        stages: [pre-commit]


      # --- PUSH STAGE: Complete test suite ---
      - id: pytest-unit-complete
        name: Run complete unit test suite
        entry: .venv/bin/python -m pytest tests/unit/ --tb=short
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: pytest-functional-complete
        name: Run complete functional test suite
        entry: .venv/bin/python -m pytest tests/functional/ --tb=short
        language: system
        pass_filenames: false
        stages: [pre-push]
