repos:
  - repo: local
    hooks:
      # --- Unit tests ---
      - id: pytest-unit-with-coverage
        name: Run unit tests with coverage and open report
        entry: bash -c 'pytest tests/unit/disable_jit --cov pyreason   --cov-report=html  && open htmlcov/index.html'
        language: system
        pass_filenames: false

      # --- Functional tests ---
      - id: pytest-functional
        name: Run functional tests
        entry: bash -c 'pytest tests/functional'
        language: system
        pass_filenames: false
        # Only run manually, not on every commit
        stages: [pre-push]
