[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[tool.ruff.lint]
# Ignore ambiguous variable name errors (E741) in interpretation files
[tool.ruff.lint.per-file-ignores]
"pyreason/scripts/interpretation/*.py" = ["E741"]
